language: java
jdk:
  - oraclejdk8
notifications:
  email: false
before_script:
  - "git clone https://github.com/felix-lang/fbuild.git"
script:
  - "fbuild/fbuild-light && build/tst"
addons:
  apt:
    packages:
      - python3