site_name: The O Language
pages:
- Home: index.md
- About: about.md
- Examples: examples.md
- Language Specification:
    - Stack: spec/stack.md
    - Variables: spec/variables.md
    - CodeBlocks: spec/codeblocks.md
    - Arrays: spec/arrays.md
theme: readthedocs
